spring:
  application:
    name: facetime

  # 默认 dev 环境
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/facetime?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root_ly

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
# 服务器相关
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    # 可全局设置上下文路径
    context-path:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.liuyuan.facetime.model.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
